### ISSUE TITLE
About Japanes character with vbac （ vbacにて日本語が文字化けします）

### ISSUE THREAD

**Issue by CallMeKohei** [vbaidiot/Ariawase#4]
日本語の部分が文字化けします。
改善事項として取り扱っていただくと嬉しいです。

環境
Windows8.1
Microsoft Excel 2013

![screen shot 2015-02-05 at 0 38 20](https://cloud.githubusercontent.com/assets/10402863/6043753/d4ef0004-acd1-11e4-81cc-c607142c236a.png)

**Comment by CallMeKohei** [comment]
文字化けする状況
---


https://github.com/CallMeKohei/TestForJapaneseCharacter


**step1:  Githubにコードを直接貼り付ける**

```vb
Option Explicit

Public Enum UriEnum
    d00_販売市場_戸建住宅 = 6
    d01_販売市場_集合住宅 = 7
    d02_販売市場_病院 = 8
End Enum

Sub test20150205()
    Debug.Print UriEnum.d00_販売市場_戸建住宅
End Sub
```

**step2: Githubからダウンロードする**

**step3: vbacでとりこむ ---> 文字化けする**
```vb
Option Explicit

Public Enum UriEnum
    d00_雋ゥ螢イ蟶ょエ_謌ク蟒コ菴丞ョ・ = 6
    d01_雋ゥ螢イ蟶ょエ_髮・粋菴丞ョ・ = 7
    d02_雋ゥ螢イ蟶ょエ_逞・劼 = 8
End Enum

Sub test20150205()
    Debug.Print UriEnum.d00_雋ゥ螢イ蟶ょエ_謌ク蟒コ菴丞ョ
End Sub
```

---
日本語を使用する背景
---
```vb
わかりやすいため
DB の View Table の Column Name に日本語が使われてるため
```

**Comment by igeta** [comment]
It's not a bug, it's a feature.
